name:                wonsz-server
version:             0.1.0.0
github:              "batkot/wonsz"
license:             MIT
author:              "Tomasz Batko"
maintainer:          "batkot@protonmail.com"
copyright:           "2020 Tomasz Batko"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Web server for simple scoreboard app
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/batkot/wonsz#readme>

dependencies:
- wonsz-core
- base >= 4.7 && < 5
- text >= 1.2 && < 2
- bytestring >= 0.10 && < 1.0
- transformers >= 0.5 && < 0.6
- microlens-platform >= 0.3 && < 1
# Servant Api dependencies
- servant-server >= 0.16 && < 0.17
- servant-auth >= 0.3 && < 0.4
- servant-auth-server >= 0.4 && < 0.5
- jose >= 0.8 && < 0.9
- utf8-string >= 1.0 && < 1.1
- aeson >= 1.4 && < 1.6
- mtl >= 2.2 && < 3.0
- time >= 1.8 && < 2.0

library:
  source-dirs: src

executables:
  wonsz-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz-server
    - warp >= 3.2 && < 3.3
    - wai-cors >= 0.2 && < 0.3
    - optparse-applicative >= 0.14 && < 0.15
    - unordered-containers >= 0.2 && < 0.3

tests:
  unit:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz-server
    - tasty >= 1.2 && < 2
    - tasty-discover >= 4.2 && < 5
  e2e:
    main:                Spec.hs
    source-dirs:         test/e2e
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz-core
    - wonsz-server
    - servant-client >= 0.16 && < 1
    - servant-auth-client >= 0.4 && < 1
    - http-client >= 0.6 && < 1
    - http-types >= 0.12 && < 1
    - warp >= 3.2 && < 3.3
    - tasty >= 1.2 && < 2
    - tasty-discover >= 4.2 && < 5
    - HUnit >= 1.6 && < 2
    - tasty-hunit >= 0.10 && < 1
    - QuickCheck >= 2.13 && < 3
    - tasty-quickcheck >= 0.10 && < 1
