name:                wonsz-core
version:             0.1.0.0
github:              "batkot/wonsz"
license:             MIT
author:              "Tomasz Batko"
maintainer:          "batkot@protonmail.com"
copyright:           "2020 Tomasz Batko"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple scoreboard library
category:            Library

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/batkot/wonsz#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 2
- bytestring >= 0.10 && < 1.0
- transformers >= 0.5 && < 0.6
- microlens-platform >= 0.3 && < 1

library:
  source-dirs: src

tests:
  unit:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz-core
    - tasty >= 1.2 && < 2
    - tasty-discover >= 4.2 && < 5
