name:                wonsz
version:             0.1.0.0
github:              "batkot/wonsz"
license:             MIT
author:              "Tomasz Batko"
maintainer:          "batkot@protonmail.com"
copyright:           "2020 Tomasz Batko"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple scoreboard app
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/batkot/wonsz#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wonsz-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz
    - servant-server >= 0.16 && < 0.17
    - servant-auth >= 0.3 && < 0.4
    - servant-auth-server >= 0.4 && < 0.5
    - jose >= 0.8 && < 0.9
    - utf8-string >= 1.0 && < 1.1
    - warp >= 3.2 && < 3.3
    - wai-cors >= 0.2 && < 0.3
    - aeson >= 1.4 && < 1.6
    - optparse-applicative >= 0.14 && < 0.15

tests:
  wonsz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz
