name:                wonsz
version:             0.1.0.0
github:              "batkot/wonsz"
license:             MIT
author:              "Tomasz Batko"
maintainer:          "batkot@protonmail.com"
copyright:           "2020 Tomasz Batko"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Simple scoreboard app
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/batkot/wonsz#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wonsz-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz

tests:
  wonsz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wonsz
